apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: fred-william-node-express-pipelinerun-
spec:
  serviceAccountName: quay-bot
  params:
    - name: github-repo
      value: https://github.com/cloud-native-garage-method-cohort/fred-william-tekton-e2e-assignment/
    - name: image-repo
      value: quay.io/faklamanu/fred-william-nextjs-app
    - name: app-name
      value: fred-william-nextjs-app
  pipelineRef:
    name: fred-william-nextjs-app
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi