apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/faklamanu/fred-william-nextjs-app
  newTag: 7221285af3f5b6c3940caaa6ad3ecd96b64d1d6a

resources:
- deployment.yaml
- service.yaml
- route.yaml
