apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/faklamanu/fred-william-nextjs-app
  newTag: 1c460037958334d8ba82fdb8596b0d5364c700c1

resources:
- deployment.yaml
- service.yaml
- route.yaml
