apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webhook-receiver
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: fred-william-nextjs-app-pipelinerun-
      spec:
        serviceAccountName: quay-bot
        params:
          - name: github-repo
            value: https://github.com/cloud-native-garage-method-cohort/fred-william-tekton-e2e-assignment
          - name: image-repo
            value: quay.io/faklamanu/fred-william-nextjs-app
          - name: app-name
            value: fred-william-nextjs-app
        pipelineRef:
          name: fred-william-nextjs-app
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 1Gi
                accessModes:
                  - ReadWriteOnce
          - name: gitops-repository
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 1Gi
                accessModes:
                  - ReadWriteOnce
          - name: git-credentials
            secret:
              secretName: git-credentials